import os
import sys
import json
import torch
import numpy as np
from torch.utils.data import DataLoader

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
from utils.seed import set_seed
from data.dataset import SparseTFIDFDataset
from models.baseline import FakeNewsMLP
from models.train import train_model
def get_predictions(model, loader, device):
    model.eval()
    all_preds = []
    all_labels = []
    all_probs = []
    
    with torch.no_grad():
        for inputs, labels in loader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            probs = torch.softmax(outputs, dim=1)[:, 1]
            _, preds = torch.max(outputs, 1)
            
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())
            all_probs.extend(probs.cpu().numpy())
            
    return np.array(all_labels), np.array(all_preds), np.array(all_probs)
from evaluation.metrics import evaluate_model

def run_evaluation(seed, model_type, input_dim, best_params=None):
    set_seed(seed)
    
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    data_dir = os.path.join(base_dir, 'data', 'processed')
    results_dir = os.path.join(base_dir, 'results')
    
    train_dataset = SparseTFIDFDataset(os.path.join(data_dir, 'X_train.npz'), os.path.join(data_dir, 'y_train.npy'))
    val_dataset = SparseTFIDFDataset(os.path.join(data_dir, 'X_val.npz'), os.path.join(data_dir, 'y_val.npy'))
    test_dataset = SparseTFIDFDataset(os.path.join(data_dir, 'X_test.npz'), os.path.join(data_dir, 'y_test.npy'))
    
    batch_size = 64
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    if model_type == 'baseline':
        model = FakeNewsMLP(input_dim=input_dim, hidden_dim=128, dropout_rate=0.5)
        lr = 0.001
    else:
        model = FakeNewsMLP(input_dim=input_dim, hidden_dim=best_params['hidden_dim'], dropout_rate=best_params['dropout_rate'])
        lr = best_params['learning_rate']
        
    model, _, _ = train_model(model, train_loader, val_loader, epochs=10, lr=lr, device=device)
    
    test_true, test_pred, test_prob = get_predictions(model, test_loader, device)
    
    # We only care about calculating metrics, not saving figures for multi-seed
    # So we bypass evaluate_model's figure saving by manually calculating or deleting the figures later
    # evaluate_model calculates it, we will just use its return value.
    metrics = evaluate_model(test_true, test_pred, test_prob, output_dir=None, prefix=None)
    return metrics

def main():
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    data_dir = os.path.join(base_dir, 'data', 'processed')
    results_dir = os.path.join(base_dir, 'results', 'metrics')
    
    with open(os.path.join(data_dir, 'preprocessing_metadata.json'), 'r') as f:
        meta = json.load(f)
    input_dim = meta['max_features']
    
    # Load PSO params (assuming it's already generated by run_all.sh)
    with open(os.path.join(results_dir, 'pso_best_params.json'), 'r') as f:
        best_params = json.load(f)
        
    seeds = [43, 44]
    results = {'baseline': {}, 'optimized': {}}
    
    for seed in seeds:
        print(f"Running Baseline for seed {seed}...")
        results['baseline'][str(seed)] = run_evaluation(seed, 'baseline', input_dim)
        print(f"Running Optimized for seed {seed}...")
        results['optimized'][str(seed)] = run_evaluation(seed, 'optimized', input_dim, best_params)
        
    with open(os.path.join(results_dir, 'multiseed_metrics.json'), 'w') as f:
        json.dump(results, f, indent=2)

if __name__ == '__main__':
    main()
